export enum ErrorNames {
    NAME_MISSING_ERROR = "Name is required",
    NAME_TYPE_ERROR = "Name must be string",
    NAME_LENGTH_ERROR = "Name must be between 1 and 15 symbols",
    TITLE_MISSING_ERROR = "Title is required",
    TITLE_TYPE_ERROR = "Title must be string",
    TITLE_LENGTH_ERROR = "Title must be between 1 and 30 symbols",
    CONTENT_MISSING_ERROR = "Content is required",
    CONTENT_TYPE_ERROR = "Content must be string",
    CONTENT_LENGTH_ERROR = "Content must be between up to 1000 symbols",
    DESCRIPTION_MISSING_ERROR = "Description is required",
    DESCRIPTION_TYPE_ERROR = "Description must be string",
    DESCRIPTION_LENGTH_ERROR = "Description length is invalid",
    WEBSITEURL_MISSING_ERROR = "Website url is required",
    WEBSITEURL_FORMAT_ERROR = "Website url does not match the pattern",
    WEBSITEURL_TYPE_ERROR = "Website must be string",
    WEBSITEURL_LENGTH_ERROR = "Website must be up to 100 symbols",
    BLOGID_MISSING_ERROR = "Blog id is required",
    BLOGID_TYPE_ERROR = "Blog id must be string",
    BODY_MISSING_ERROR = "Request body is required",
    ID_MISSING_ERROR = "ID is required",
    ID_TYPE_ERROR = "ID must be a string",
    ID_EMPTY_ERROR = "ID must not be empty",
    ID_FORMAT_ERROR = "Incorrect format of Mongo ID",
}