export const EndpointList = {
  EMPTY_PATH: "",
  SLASH_PATH: "/",
  TESTING_PATH: "/api/testing",
  TEST_DELETE_ALL: "/all-data",
  BLOGS_PATH: "/api/blogs",
  BY_ID: "/:id",
  POSTS_BY_BLOG_ID: "/:id/posts",
  POSTS_PATH: "/api/posts",
  USERS_PATH: "/api/users",
  AUTH_PATH: "/api/auth",
  LOGIN_PATH: "/login",
  ME_PATH: "/me",
  COMMENTS_PATH: "/api/comments",
  COMMENTS_BY_POST_ID: "/:id/comments",
};
